name: vertx-redis-client (4.x)
on:
  push:
    branches:
      - '4.x'
  pull_request:
    branches:
      - '4.x'
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
          - os: ubuntu-latest
            jdk: 17
    uses: ./.github/workflows/ci.yml
    with:
      branch: 4.x
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
    secrets: inherit
  Deploy:
    if: ${{ github.repository_owner == 'vert-x3' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: CI
    uses: ./.github/workflows/deploy.yml
    with:
      branch: 4.x
      jdk: 8
    secrets: inherit
